spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Auth0 / Spring Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH0_JWKS_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE}
auth0.client-id=${AUTH0_CLIENT_ID}

# Server Port
server.port=${PORT:8080}    